<?php

namespace AppBundle\Repository;

/**
 * ActividadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadesRepository extends \Doctrine\ORM\EntityRepository
{
}
