<?php

namespace AppBundle\Repository;

/**
 * CoordinadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordinadoresRepository extends \Doctrine\ORM\EntityRepository
{
}
