<?php

namespace AppBundle\Repository;

/**
 * DepartamentosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartamentosRepository extends \Doctrine\ORM\EntityRepository
{
}
