<?php

namespace AppBundle\Repository;

/**
 * DesgloseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesgloseRepository extends \Doctrine\ORM\EntityRepository
{
}
