<?php

namespace AppBundle\Repository;

/**
 * FacultadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacultadesRepository extends \Doctrine\ORM\EntityRepository
{
}
