<?php

namespace AppBundle\Repository;

/**
 * ModulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModulosRepository extends \Doctrine\ORM\EntityRepository
{
}
