<?php

namespace AppBundle\Repository;

/**
 * OrganismosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganismosRepository extends \Doctrine\ORM\EntityRepository
{
}
